### PR TITLE
Make ReflectionHelper more static class friendly

### PR DESCRIPTION
**Pull request by TheMulhima**
Static classes does not work with generic type parameters. Asking for type is a bit more annoying but this seems like a better solution than creating 2 more overloads.

### CODE REVIEW

**Comment by TheMulhima** [comment]
Actually I'm not really sure anymore. Probably 2 more overload is better

**Comment by fifty-six** [comment]
Overloads can be convenient, but your call - I'm fine with whatever.

**Comment by TheMulhima** [comment]
I'll probably go for the extra overloads

**Comment by fifty-six** [comment]
I think omitting them for static types is probably what you want tbh, more consistent in general and you usually don't see them too much.

**Comment by TheMulhima** [comment]
> I think omitting them for static types is probably what you want tbh, more consistent in general and you usually don't see them too much.

Probably true but will be useful if we are trying to
1) make this ReflectionHelper the main one people use
2) make it easier to reflect other mod's classes (which are more likely to be static)
3) Probably could be copied over to silk song API?

**Comment by TheMulhima** [comment]
Upload of the test to verify class is working
[newReflectionHelperTest.txt](https://github.com/hk-modding/api/files/7953208/newReflectionHelperTest.txt)

**Comment by fifty-six** [comment]
GitHub close pull requests when I rebase challenge (impossible) - a92c39fbe7bfe22f77df1f00eb3cdd42d8eeeb73

**Pull request closed without merging**
