### PR TITLE
Improved scrolling in mod menus 

### PR DESCRIPTION
**Pull request by PrashantMohta**
- Closer to vanilla scroll bar
- Adds scroll wheel support
- Fixes scrolling via keyboard/joystick selection

### CODE REVIEW

**Comment by fifty-six** [comment]
The scroll wheel support on this is super janky, it goes in like chunks if it goes at all, easy check is against the QoL modules list

**Comment by PrashantMohta** [comment]
Seems like it only scrolls when the cursor is on the text element and not the empty space, making this a draft till I can take another look at it, for a fix.

**Comment by PrashantMohta** [comment]
That should do it

**Comment by fifty-six** [comment]
Thanks!

**Pull request merged**
