### PR TITLE
Actually use the changed value after invocation

### PR DESCRIPTION
**Pull request by PrashantMohta**

### CODE REVIEW

**Comment by SFGrenade** [comment]
It does literally nothing except being good code convention. Maybe another commit to change the naming in the `SetPlayerVector3` method to have the same names for params and stuff.

**Comment by fifty-six** [comment]
This literally doesn't do anything but slightly change internal variable names?

**Comment by PrashantMohta** [comment]
This commit changes the variable that is used for invocation of the hook delegates and the same value is actually set internally. Current implentation does not set the variable that is modified by the delegates. (Probably need to see this whole function instead of just the diff)

https://github.com/hk-modding/api/pull/71/commits/edf3760cf5a39467f3a57b687fd6421af2b986f0

**Comment by fifty-six** [comment]
Oh I see, my bad.

**Pull request merged**
