### PR TITLE
Ignore disabled mod folder

### PR DESCRIPTION
**Pull request by SFGrenade**

### CODE REVIEW

**Comment by fifty-six** [comment]
I don't think this is necessary because the disabled folder would contain folders and the loader only looks one deep.

**Comment by SFGrenade** [comment]
yes, but it would fuck with people updating from 1.4.3.2, when they still have dll files in the disabled folder thanks to old(current) modinstallers

**Comment by fifty-six** [comment]
In theory I'd want to clear those out when migrating but special casing it might be reasonable. I'd just `.Except(Directory.GetFiles(Path.Combine(managed, "Disabled)))` instead of branching on every dir though.

**Comment by SFGrenade** [comment]
brb rewriting history

**Pull request merged**
