### PR TITLE
Preload Assets

### PR DESCRIPTION
**Pull request by HKLab**

### CODE REVIEW

**Comment by fifty-six** [comment]
What's the point of this if mods can trivially call `Resources.Load("")` themselves? Also why is it done twice with `.Load("", t)` and `FindObjectsOfTypeAll`? The main point of the preloader was to avoid multiple mods avoiding scenes themselves as it caused unnecessary work and was generally poorly done across each mod. This should also really be separated from the general preloading scenes bit if it is necessary. Sorry I took a while to get to this

**Comment by HKLab** [comment]
`Resources.Load()` requires the path of the object relative to the Resources folder, ie `A/B/C`.

**Comment by HKLab** [comment]
`Resources.FindObjectsOfTypeAll` includes all currently loaded objects, but does not include unloaded objects, `Resources.LoadAll` is used to load unloaded objects

**Comment by fifty-six** [comment]
If you specify the empty string it's a load-all from resources anyways, no? It seems like `Resources.Load("", t)` is the call you do anyways, not a specified asset path. Aside from that, given you can do this pretty easily from your own mod without a downside, why is it part of the preloader?

**Comment by HKLab** [comment]
I will think of other ways to make it easier for modder to find the assets path

**Comment by fifty-six** [comment]
Resources.LoadAll("") doesn't though, I've also already found the paths at some point - have them saved if i can find them

**Comment by HKLab** [comment]
Assets like Prefab are in resources.assets but cannot be loaded via `Resources.Load`, they are loaded before the game starts

**Comment by fifty-six** [comment]
How does this PR let you get them then if you can't Resources.Load/LoadAll them? Sorry I don't get it still

**Comment by HKLab** [comment]
Because of this, I need to get them back via Resources.FindObjectsOfTypeAll

**Comment by fifty-six** [comment]
I mean - if that's the requirement can that still not be done after loading by mods themselves relatively easily?

**Comment by HKLab** [comment]
Sorry, I still can't understand what you mean because of the translation problem

**Comment by fifty-six** [comment]
Alright so, just to reiterate my concerns so I can double check why this is necessary/wanted
- What's the purpose of using this over `Resources.LoadAll("")` + `Resources.FindObjectsOfType<T>` from within your own mod? The preloader itself was to avoid duplication of loading scenes and to centralize the resource as it was difficult to get right while remaining performant. I've had success myself fairly easily doing [Resources.LoadAll](https://github.com/Sid-003/HKTwitch/blob/master/HollowTwitch/Commands/Game.cs#L24) and just finding the objects in-mod when needed [e.g.](https://github.com/Sid-003/HKTwitch/blob/master/HollowTwitch/Commands/Area.cs#L139)
- Why do this in-api?
- Why does this load several scenes when resources themselves can be force loaded with `LoadAll`? Does loading scenes enable finding resources that can't be forced with `LoadAll`? 
- Can't mods (if they were provided the ability to figure out resource paths) do `Resources.Load` themselves?

**Comment by HKLab** [comment]
`Resources.LoadAll` cannot find Prefab and other Assets, you can print the return value of `Resources.LoadAll` yourself. Why use it in HKTool because I forgot to delete it

**Comment by fifty-six** [comment]
Can Resources.Load find it (if you have the path), or do you have to actually load the scene? wdym forgot to delete it

**Comment by HKLab** [comment]
> Can't mods (if they were provided the ability to figure out resource paths) do Resources.Load themselves?
Regarding this issue, you can restore the HK project with uTinyRipper and see what's in the Resources folder.

**Comment by fifty-six** [comment]
Yeah, that's what I mean - I've done it myself. Given that, you can find the paths - so is loading the scenes still necessary or no? If it isn't then why add this, otherwise I get the need

**Comment by HKLab** [comment]
> Does loading scenes enable finding resources that can't be forced with `LoadAll`?

Yes, they are loaded into memory by unity when the scene that references them is loaded and can be found by `Resources.FindObjectsOfTypeAll`

**Comment by HKLab** [comment]
> Why do this in-api?

Because if it doesn't, then the mod can only get some resources through `Resources.FindObjectsOfTypeAll<T>().First(x => x.name == "xxx")`, and it may be executed more than once

**Comment by fifty-six** [comment]
Do you think that's worth the complexity? I feel like as that's largely done at startup and doesn't have a huge overhead delegating it to in-mod wouldn't be *too* bad. I haven't abused it a whole lot though and being able to specify objects more directly than dumping paths does seem nice. If you think it's worth I'd be okay working with this PR, just think it's a lot of complexity for something that's not as huge a resource drain as something like scene loading. 

Somewhat alternatively, there's a trick with generics where you can cache a generic lookup such as `Resources.FindObjectsOfTypeAll<T>` using a sort of lazy singleton which would be much simpler while still allowing for easy mod usage, which I think would be decent alternative if you'd be okay looking at an impl of that which I would be fine writing as an example.

**Comment by HKLab** [comment]
Well, what do you say should be done next?

**Comment by HKLab** [comment]
I hope to fix it in these few weeks, don't make api72 wait too long

**Comment by fifty-six** [comment]
Do you have any examples of you using this? I'd like to try a simpler impl and see if that works out and if not we can go from there.

**Comment by HKLab** [comment]
class A: Mod{
public override List<(int, string, Type)> GetPreloadAssetsNames(){
return new() {
(32,"AAA",typeof(BBB))
};
}
public override void Initialize(Dictionary<string, Dictionary<string, GameObject>> preloadedObjects, Dictionary<int, Dictionary<string, UnityEngine.Object>> preloadedAssets){
var asset=preloadedAssets[32]["AAA"];
}

}

**Comment by fifty-six** [comment]
BBB? Is there an actual asset I can test with that you use?

**Comment by HKLab** [comment]
sorry, we do not have that.  Because most of my mods currently use the api encapsulated by hktool

**Comment by HKLab** [comment]
For example audioclip mimic_spider_scream in sharedassets109

**Comment by fifty-six** [comment]
Ah, thanks

**Pull request closed without merging**
