### PR TITLE
updated windows build to 1.5.77

### PR DESCRIPTION
**Pull request by mandar1jn**
I'm too lazy to use steam CMD so here is just the windows version

### CODE REVIEW

**Comment by mandar1jn** [comment]
It works now. IDK what went wrong with the first zip

**Comment by fifty-six** [comment]
.77 is the beta, why update the API?

**Comment by mandar1jn** [comment]
Didn’t you do the same for 1.5?

**Comment by mandar1jn** [comment]
I figured the same would apply here

**Comment by fifty-six** [comment]
1.5 was a major version change and thus we wanted to get the API ready and all, not really a point to minor versions.

**Pull request closed without merging**
