### PR TITLE
Faster Reflection

### PR DESCRIPTION
**Pull request by HKLab**

### CODE REVIEW

**Comment by fifty-six** [comment]
This is cool but I'd prefer not to rely on Unity mono internals, as-is [reading from an offset isn't necessarily guaranteed to work out](https://github.com/dotnet/runtime/issues/43285#issuecomment-707858370), but actually transmuting the handle is a bit much even more than that. There's also a fairly significant amount that can be done without internal access still. As far as direct ret goes I had some issues with that regarding not having the exact signature work out but if that works then I'd be happy to have that included.

**Comment by fifty-six** [comment]
If you want to use offsets, I'd be okay with the use of `UnsafeUtility.GetFieldOffset` as that's portable across Unity mono versions and should be effectively the same. You don't need to use the pointers though, `UnsafeUtility` has the ability to read at offsets already. I was half-meaning to try that at some point but I never got around to it.

**Comment by HKLab** [comment]
No,`UnsafeUtility.GetFieldOffset` makes reflection slower

**Comment by HKLab** [comment]
I found a phenomenon that the running speed of the code with the same function is very different in HKTool and MAPI

**Comment by HKLab** [comment]
`FieldInfo.DeclaringType` is too slow

**Comment by fifty-six** [comment]
Is this GC safe?

**Comment by HKLab** [comment]
I think yes, there should be no possibility of gc inside these codes

**Comment by fifty-six** [comment]
Do you have any benches for this? Just want to see how significant an improvement it is first

**Comment by HKLab** [comment]
Run instance field get/set 1000000 times
Testing code: https://github.com/HKLab/ReflectionTest/blob/master/scripts/Test.cs#L112-L118
old: 198ms
new: 139ms

**Pull request merged**
